# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

before_all do
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "pixd-bemn-dsxk-kmpk"
  ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"]  = "+1 (832) 8462410"
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore",  
    ) 
    increment_build_number
    gym(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner"
    )
    upload_to_testflight(  
      changelog: "Upload for Test",   
      notify_external_testers: true,  
      groups: ['Beta'],
      distribute_external: true
    )
  end

  desc "Upload"
  lane :upload do |options|
    match(type: "appstore", readonly: true) 
    increment_build_number
    gym(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner"
    )
   
  end


end
